spring.application.name=seller-ai-automation
# MongoDB Config
spring.data.mongodb.uri=mongodb://localhost:27017/seller_ai_db

# Server Config
server.port=8080

# Thymeleaf Config
spring.thymeleaf.cache=false

# Groq AI Config (Using Llama3 for speed)
groq.api.key=xyz
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile
# Logging
logging.level.com.sellerhq=DEBUG